### ISSUE TITLE
Handling empty clusters

### ISSUE THREAD

**Issue by andreyurch** [ramachandran-lab/pong#1]
Hello, the python and the pong are newest.

For K=2, there is 1 mode across 1 run.
For K=3, there is 1 mode across 1 run.
For K=4, there is 1 mode across 1 run.
For K=5, there is 1 mode across 1 run.
For K=6, there is 1 mode across 1 run.
For K=7, there is 1 mode across 1 run.
For K=8, there is 1 mode across 1 run.
For K=9, there is 1 mode across 1 run.
For K=10, there is 1 mode across 1 run.
For K=11, there is 1 mode across 1 run.
For K=12, there is 1 mode across 1 run.
For K=13, there is 1 mode across 1 run.
For K=14, there is 1 mode across 1 run.
For K=15, there is 1 mode across 1 run.
For K=16, there is 1 mode across 1 run.
For K=17, there is 1 mode across 1 run.
Matching clusters across K
/usr/local/lib/python2.7/site-packages/pong/dist_metrics.py:32: RuntimeWarning: invalid value encountered in double_scalars
  return 1 - np.sqrt(np.sum(np.array(j)**2))/np.sqrt(2*len(j))
Finding best alignment for all runs within and across K

And never finishes the job

**Comment by sohinir** [comment]
Thank you for posting this issue! We have seen this issue generated when essentially empty clusters are inferred (that is, clusters with membership coefficients on the order of 10^{-5} for all individuals). Is that the case in your data? Did you use fastStructure to generate your Q matrices, by any chance? We are working to have pong deal with this error by identifying the smallest K value with two empty clusters and removing that K value and any larger K value from the filemap while proceeding align all other Q matrices. If you remove K \geq 17 from your filemap, I'm guessing pong runs - is that true?

**Comment by andreyurch** [comment]
Thank you for the explanation.  Yes, this is a fastSTRUCTURE output.   If I plot only k=11-17 it works, but for the wider range (K2-17) doesn't

**Comment by sohinir** [comment]
Hello - would you be able to send a minimum working example? You can create dummy labels for the individuals. We just need to recreate the issue to debug.

**Comment by Kenizzer** [comment]
Here is a working example, generated by fastSTRUCTURE, of the error for debugging, the program stalls at K=8 as this contains file contains empty clusters.

[Error_example_pong.tar.gz](https://github.com/ramachandran-lab/pong/files/1604495/Error_example_pong.tar.gz)

**Comment by ntakebay** [comment]
Did you figure out the bug?  I encountered this, and the problem occurs when --dist_metric jaccard (default).  When I specify the other dist_metric, pong doesn't get stuck at the stage. I hope this info helps to debug the issue.

**Comment by abehr** [comment]
We have a potential fix, but we have been hesitant to implement it because it would involve implementing somewhat-arbitrary thresholds for minimum cluster membership.

The issue occurs when there's a cluster for which no individual in the dataset has any (significant) membership. Based on the datasets I've seen where this happens, I think it usually indicates that there isn't any finer structure in the data (at least, not that the clustering alg could find), i.e. _K_ is too high. If you think there's something more biologically relevant going on that would actually be worth visualizing in pong, though, I would be curious to hear about it. The 'fix' is something we definitely could add.
