### ISSUE TITLE
Custom colors for visualization

### ISSUE THREAD

**Issue by mariajpalma** [ramachandran-lab/pong#15]
Hi, I have a question, is there any way to assign a color to a reference population? Because I am plotting admixture for different test populations but I can not make my reference population always the same color.  I am using always the same pop order and the color file is the same.

Thanks

Majo

**Comment by shahamat** [comment]
Hi, 

I am looking into this for you but need a little more information. 

(1) Are you plotting multiple values of K in the same run or just one? 
(2) Do you have multiple Q matrices per value of K?

Thanks,
Sahar

**Comment by mariajpalma** [comment]
1. Just one
2. Yes

The problem is that I have multiple admixture plots with different target populations, but I am always using the same reference panels, so I have different plots, but I would like to know if there is any way to get my references in the same color.

**Comment by shahamat** [comment]
One more question, are you running pong once for each of the target populations? i.e. if you have three admixture runs, you run pong three times using a different ind2pop file every time.

**Comment by mariajpalma** [comment]
I have 3 different Q matrices per each target population and I run pong once (the colors are consistent), but for the next target population, I am running pong again (the reference population colors change). As I understand it is because the color is related to the Q columns, but I would like to know if I can do it without reordering the colors manually each time I run pong

**Comment by shahamat** [comment]
Unfortunately the code does not currently support this; we may add this functionality in the future.

**Comment by mariajpalma** [comment]
ok, thanks :)

**Comment by abehr** [comment]
Hi Majo,

Your understanding is correct: the colors may seem inconsistent between runs because pong assigns colors to clusters (i.e. Q columns), rather than to populations. As you mentioned, it is possible to achieve the visual consistency you want by changing the order of the colors in your `COLOR_LIST` file.

In case it's helpful to you, here's a bit more information on how pong assigns colors to clusters (at least in this case, where you're plotting only one K-value): The ordering of colors in the `COLOR_LIST` file corresponds with the bottom-up order of clusters (i.e. the first color in the file corresponds with the bottom cluster). Here's a screenshot for clarity:

<img width="582" alt="Screen Shot 2020-03-20 at 7 39 17 PM" src="https://user-images.githubusercontent.com/6844407/77213829-ad3f9580-6ae2-11ea-9be1-e9951b6d84ef.png">

Note that, for a given Q-matrix, the clusters maintain a vertical order (i.e. they are stacked vertically for each individual, and always appear in the same order). You can look at admixed individuals to discern the order, given that individuals in reference populations might have 100% membership in a single cluster.
