### ISSUE TITLE
Custom Color list

### ISSUE THREAD

**Issue by SanchitaB** [ramachandran-lab/pong#2]
Hi,

I made a custom color list with 26 colors (attached)(https://github.com/ramachandran-lab/pong/files/1154676/Color_list.txt)
 I ran 10 replicates for K=12. When I run Pong it is giving me a Warning:
The custom color file provided does not contain enough colors for visualization. Continue using default colors? (y/n): 

I have listed more colors than K(max). Any insight would help.
Thanks,
Sanchita

**Comment by shahamat** [comment]
Hi Sanchita,

The issue was resolved when I changed the formatting of Color_list.txt. It turns out that some files that originate from DOS/Windows use "^M" to signify a new line, whereas Unix files use "\n". Pong was expecting the latter, and therefore could not parse the colors file correctly. I have attached a modified file, with the same colors as yours but with the Unix formatting. Give that a try, and let me know if that helps.

Best,
[unix_color_list.txt](https://github.com/ramachandran-lab/pong/files/1156091/unix_color_list.txt)


Sahar

**Comment by SanchitaB** [comment]
Thanks a lot. It worked.

-Sanchita
On Jul 18, 2017, at 7:10 AM, shahamat <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Sanchita,

The issue was resolved when I changed the formatting of Color_list.txt. It turns out that some files that originate from DOS/Windows use "^M" to signify a new line, whereas Unix files use "\n". Pong was expecting the latter, and therefore could not parse the colors file correctly. I have attached a modified file, with the same colors as yours but with the Unix formatting. Give that a try, and let me know if that helps.

Best,
unix_color_list.txt<https://github.com/ramachandran-lab/pong/files/1156091/unix_color_list.txt>

Sahar
