### ISSUE TITLE
install fails on Mac Sierra

### ISSUE THREAD

**Issue by angelesdecara** [ramachandran-lab/pong#3]
Hi,

I've got python and pip, but when I type
% pip install pong
I obtain this error

Collecting pong
  Using cached https://files.pythonhosted.org/packages/b7/e3/f253cdbf53e04285fc784ea33e4ba317e9a9fb8e430e3fc363a1fd4231f1/pong-1.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0j/t7r1qj148xj_zz0059b_9cw80000gp/T/pip-install-nkkmayat/pong/setup.py", line 5, in <module>
        execfile("pong/__init__.py")
    NameError: name 'execfile' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0j/t7r1qj148xj_zz0059b_9cw80000gp/T/pip-install-nkkmayat/pong/

All help will be greatly appreciated.
Thanks!

**Comment by shahamat** [comment]
The problem seems to be caused by your Python version. pong requires Python 2 (version 2.7.8 or newer), and it seems like you are using Python 3. There are several workarounds, the easiest of which is to install Anaconda, create an environment with Python 2, and install pong within that environment (https://conda.io/docs/user-guide/tasks/manage-environments.html).

Let us know if that solves your problem!

**Comment by nehasavant** [comment]
Thanks to angelesdecara for bringing this issue up and to shahamat for responding so quickly! This helped me solve the very same error I was getting. I used a Python 2 conda environment.
