### ISSUE TITLE
Output aligned matrices

### ISSUE THREAD

**Issue by RvV1979** [ramachandran-lab/pong#32]
Hi Aaron, 

Pong is great in its user-friendly interface and has some excellent options. However, sometimes I need more customisation options and would like to generate more elaborate plots in, e.g., R. For example, to include sample IDs and multiple grouping factors. However, the run files in Pong's output directory are copies of the input file matrices and these are therefore not yet aligned across different k. 

Would it be possible for pong to output the aligned Q matrices ?

Thanks.

**Comment by abehr** [comment]
Hello,

Thanks for the feedback - we definitely appreciate it! 

pong does not output pre-aligned _Q_-matrices, but it would not be difficult to add this functionality. Currently, pong _does_ output permutation matrices both within and across K, which should make this easy to do in R (e.g. `run_df <- run_df[, c(new_column_permutation)]`) -- since the lines of the permutation matrices and the output _Q_-matrices are both linked with the same runIDs. 

There are two (historic) reasons for our current output format (rather than outputting pre-aligned run files):
1. It's compatible with CLUMPP/CLUMPAK/Distruct I/O formats, in case users migrating from those programs wanted to compare results
2. The permutation matrices allow users to align their runs relative to a different representative run than the one pong chose (if desired)

However, we could generate a post-processing script (or potentially add this functionality into pong) if it would be helpful to you and other users. 

I would also be interested to learn a bit more about the additional plot customizations you mentioned. Of course, some use cases are unique, but we like to keep aware of common ones (for example, adding sample IDs) so that we can continue improving pong in future releases.

**Comment by RvV1979** [comment]
Hi Aaron, 

Thanks for the positive response and for your primer on how to use the permutation matrices. That is very helpful and enough information for me to do what I want. 

With regard to customizations, as mentioned above, I can confirm that showing sample IDs is one of the desired features. Also, showing multiple grouping labels would be useful.
