### ISSUE TITLE
Reorder columns within each population

### ISSUE THREAD

**Issue by lukaskon** [ramachandran-lab/pong#33]
Hello, I read in the manual that "The first column contains population labels from the ind2pop file; the top-to-bottom order of these labels will be the left-to-right order in which the population are displayed in pong’s visualization." But I have a large dataset and would prefer to have them order according to cluster membership. Is there a way to do this? 

Example, I would like the columns to start with samples that have blue membership in this picture.
![image](https://github.com/ramachandran-lab/pong/assets/92044283/da52d02c-6154-4b0f-a8f4-ad21f46c7239)
 
Thanks!

**Comment by abehr** [comment]
Hello! What you're referring to in the manual is how to specify the left-to-right order of the populations themselves (not the individuals within each population). Within each population, the individuals (i.e. individual columns) are indeed sorted according to their cluster membership -- specifically, by increasing membership in the cluster with the highest overall membership for that population at the highest value of K. The picture you provide doesn't show K>3 but my guess is that's what's going on. If not, definitely let me know because that would be a bug. 

The reason we sort by membership at the highest provided value of K is that sorting by membership at lower K (esp K=2) tends to produce sort orders that look random as K increases and clusters split. We also don't want to sort the individuals differently at each value of K because then it is not possible to compare an individual's cluster membership across multiple values of K in the visualization.

However, if you want this sort behavior, here are a few options I can think of:
- If you want to sort the entire set of samples according to cluster membership, regardless of population labels, you can simply leave out the `-i` and `-n` arguments.
- If you want to keep the individuals segmented by population, but specifically sort them by their membership in the major cluster for each value of K (such that the individuals are sorted differently at each K), you could run pong separately for each value of K (not ideal, I realize).
- If you want to sort per-population across K according to specifically K=2 blue cluster membership, pong doesn't do this by default, but it shouldn't be too tricky to modify the source code to produce this output. 

Let me know if this helps!

**Comment by lukaskon** [comment]
Thanks for the quick response! Below is the full picture- I just had it cutoff before. Maybe I am misunderstanding this, but shouldn't I expect to see the same cluster color (probably red or blue) in the far left column for each population (assuming at least one individual has partial membership with that cluster)?

![image](https://github.com/ramachandran-lab/pong/assets/92044283/40ddf210-6841-46f1-9f3d-64f3d4acc3f9)

**Comment by abehr** [comment]
Ahh, I see. So it depends on the population. At K=4, pops 0 & 7 are sorted by membership in the green cluster, pop 1-3 are sorted by the blue, pop 4-6 are sorted by red, etc. -- it's according to the "major cluster" for each population (i.e. whichever cluster has the highest overall membership across the whole pop). 

I can see how this sort order yields kind of an unhelpful display here, though. I'm wondering what kind of options would be most helpful. Maybe the issue is the vertical sorting (i.e. stacking) of the clusters? There are reasons we maintain that across the entire visualization, but it could be useful to add that as an option (e.g. pop 5 is sorted by red, which makes sense, but maybe it should be below green in the stack). Or, maybe it would be useful to have an option to sort the individuals in every population by their membership in the dataset's major cluster. This would be bad for cases where populations segment very well into different clusters, but would be good in this case.

**Comment by lukaskon** [comment]
Now I understand! There's really not a nice way to sort that works for everyone's goals so maybe more options would be beneficial. Like you said, I would value the option to reorder each pop manually (or have the option to have all pops order the clusters in the same way). Here is an image that is closer to the visualization I am going for (not the same dataset):

![image](https://github.com/ramachandran-lab/pong/assets/92044283/9b423039-eef8-4a3e-95ad-27ed992356f9)

**Comment by abehr** [comment]
Gotcha - I think adding an option in the viz to sort by any given cluster would be a great feature. Will add this to the list of potential improvements!
