### ISSUE TITLE
Rotating population to 90 degree

### ISSUE THREAD

**Issue by itsmestewart** [ramachandran-lab/pong#34]
Hello.

Thanks  for your truly amazing tool(Pong). I would like to know. How can I rotate the population labels on x axis, let say to 90 degree to avoid population labels from overlapping.

Best regard
Stewart

**Comment by sohinir** [comment]
The rotation angle is currently fixed in pong to 45 degrees, on line 31 in https://github.com/ramachandran-lab/pong/blob/master/static/pong.js. `labelRotate = 45`. You could alter this and run pong by hand as opposed to installing using pip, if you feel comfortable with altering the code. If not, I would suggest running pong without labels and then adding them yourself using a program like Adobe Illustrator, importing the svg or pdf that pong outputs as a download. Good luck!

**Comment by itsmestewart** [comment]
Dear Sohinir,

I truely appreciate your response and informative clarfication.

Thank you.
