### ISSUE TITLE
Share html with others

### ISSUE THREAD

**Issue by baozg** [ramachandran-lab/pong#5]
Can pong add output html to visualize the result?I can only open the html page in my own machine. 
When I want to share with others for discussions, I can only print all barplots to PDF, but can not sava the html as output result.

**Comment by abehr** [comment]
Hi Zhigui,

It is not possible to download the full interactive visualization because pong is a full web application that requires an actively-running server to interact with the html (client). That's why you'll just see a bare skeleton of the page if you try to download the html.

However, the full interactive visualization can be shared with others while the pong server is running on your machine. For example, anyone else on your network can access the visualization in their own web browser by navigating to `[your_local_IP_address]:4000`.

Hope this helps!

**Comment by baozg** [comment]
How about html like [multiqc](https://multiqc.info/) generated?
It insert the data into the html, so can send the html to anyone who can connect the web.
Actually the pong could do this because Q-martix is very small, load it and then visualize by the D3.js?

**Comment by sohinir** [comment]
Hi Zhigui - just following up; this isn't currently a feature we have incorporated but we will consider for the future. The Q matrix is pretty easy to store but we also want pong to be flexible in terms of being able to handle many Q matrices across many values of K (and multiple Q matrices for a given value of K). So the type of functionality you are proposing is not something we have implemented. Hopefully the print features, combined with sharing with others on your network, will help you for now!
